name: Sync branches to Hugging Face Spaces

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - branch: main
            space: OLLAMA-Server-Test
          - branch: dev
            space: OLLAMA-Server-Dev

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
          ref: ${{ matrix.branch }}   # ✅ ensures we’re on the actual branch

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          echo "🔄 Syncing branch '${{ matrix.branch }}' to Space '${{ matrix.space }}'"
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"

          git push --force \
            https://Dfrost8-2:$HF_TOKEN@huggingface.co/spaces/Dfrost8-2/${{ matrix.space }} \
            ${{ matrix.branch }}:main
