---

title: Ollama + Qwen2.5 (3B) — Baseline
emoji: 🧠
colorFrom: blue
colorTo: green
sdk: docker
sdk_version: '1.0'
app_file: start.sh
pinned: false
license: apache-2.0

---


name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push --force https://Dfrost8-2:$HF_TOKEN@huggingface.co/spaces/Dfrost8-2/OLLAMA-Server-Test main
